# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestweathershopper2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testweathershopper2(self):
    # Test name: test_weathershopper2
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://weathershopper.pythonanywhere.com/")
    # 2 | setWindowSize | 974x1032 | 
    self.driver.set_window_size(974, 1032)
    # 3 | click | css=.octicon | 
    self.driver.find_element(By.CSS_SELECTOR, ".octicon").click()
    # 4 | click | css=.text-center:nth-child(1) .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(1) .btn").click()
    # 5 | click | css=.octicon | 
    self.driver.find_element(By.CSS_SELECTOR, ".octicon").click()
    # 6 | click | css=.row:nth-child(3) > .text-center:nth-child(1) > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) > .text-center:nth-child(1) > .btn").click()
    # 7 | click | css=.text-center:nth-child(5) > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(5) > .btn").click()
    # 8 | click | id=cart | 
    self.driver.find_element(By.ID, "cart").click()
    # 9 | click | css=span:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(1)").click()
    # 10 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 11 | type | id=email | ilu@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("ilu@gmail.com")
    # 12 | click | id=card_number | 
    self.driver.find_element(By.ID, "card_number").click()
    # 13 | type | id=card_number | 5125 5151 5011 7824
    self.driver.find_element(By.ID, "card_number").send_keys("5125 5151 5011 7824")
    # 14 | click | id=cc-exp | 
    self.driver.find_element(By.ID, "cc-exp").click()
    # 15 | type | id=cc-exp | 12 / 27
    self.driver.find_element(By.ID, "cc-exp").send_keys("12 / 27")
    # 16 | click | id=cc-csc | 
    self.driver.find_element(By.ID, "cc-csc").click()
    # 17 | type | id=cc-csc | 005
    self.driver.find_element(By.ID, "cc-csc").send_keys("005")
    # 18 | click | css=.iconTick | 
    self.driver.find_element(By.CSS_SELECTOR, ".iconTick").click()
    # 19 | mouseOut | css=#submitButton path:nth-child(16) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
